
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/Dockerfile to edit this template

FROM openjdk:19
EXPOSE 8080
ADD /target/spring5-jokes-app-v2.jar spring5-jokes-app-v2
ENTRYPOINT ["java","-jar","spring5-jokes-app-v2"]